### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [realOxy/M3UAndroid#75]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5928486717#L1100

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/104c2ec47f9d159c18bef8ead0a1b4e98a34deb8

**Comment by linsui** [comment]
[diff.html.zip](https://github.com/realOxy/M3UAndroid/files/13937984/diff.html.zip)

**Comment by realOxy** [comment]
@linsui @licaon-kter What's the meaning? I can't understand, what should I do?

**Comment by licaon-kter** [comment]
@realOxy was this apk https://github.com/realOxy/M3UAndroid/releases/tag/v1.14.0-alpha06 really built from https://github.com/realOxy/M3UAndroid/commit/9d6211a9d7bf4dc5e0afee8e954b03344aca3b5a ?

If so... maybe try to rebuild it from command line, but first clean up any caches. Put the APK here or there and ping us to retest

**Comment by realOxy** [comment]
@licaon-kter oh sorry, let me push all local commits and release a new version now.

**Comment by realOxy** [comment]
> @realOxy was this apk https://github.com/realOxy/M3UAndroid/releases/tag/v1.14.0-alpha06 really built from [9d6211a](https://github.com/realOxy/M3UAndroid/commit/9d6211a9d7bf4dc5e0afee8e954b03344aca3b5a) ?
> 
> If so... maybe try to rebuild it from command line, but first clean up any caches. Put the APK here or there and ping us to retest

Hi, I have released a new one. Based latest commit.

**Comment by realOxy** [comment]
@licaon-kter Do I need to close this issue before ci can be re-executed?

**Comment by licaon-kter** [comment]
We'll retest and close if confirmed

**Comment by licaon-kter** [comment]
still fails https://gitlab.com/fdroid/fdroiddata/-/jobs/5936278922#L1104

**Comment by realOxy** [comment]
> still fails https://gitlab.com/fdroid/fdroiddata/-/jobs/5936278922#L1104

How can I look for their difference

**Comment by licaon-kter** [comment]
The APK is in right sidebar Browse -> tmp -> https://gitlab.com/fdroid/fdroiddata/-/jobs/5936278922/artifacts/file/tmp/com.m3u.androidApp_92.apk

**Comment by licaon-kter** [comment]
diff log: 
[m3u92.log](https://github.com/realOxy/M3UAndroid/files/13948520/m3u92.log)


All those `const` sound like https://gitlab.com/fdroid/fdroiddata/-/issues/3138

**Comment by realOxy** [comment]
@licaon-kter It means I should build it in compose compiler 1.5.6 ? 🤔
https://github.com/realOxy/M3UAndroid/blob/93a55c1a0e7f21ca11bf3e5c6e9b63f221323d0c/gradle/libs.versions.toml#L40

**Comment by licaon-kter** [comment]
If you can build an APK with that we could test

**Comment by realOxy** [comment]
@licaon-kter released: https://github.com/realOxy/M3UAndroid/releases/tag/v1.14.0-alpha08

**Comment by linsui** [comment]
Since M3U 1.13.6 already uses complier 1.5.7, that shouldn't be the problem.

**Comment by realOxy** [comment]
> Since M3U 1.13.6 already uses complier 1.5.7, that shouldn't be the problem.

This software has never been successfully uploaded to f-droid before. Were the previous builds not affected by the compose compiler?

**Comment by linsui** [comment]
1.13.6 is the first version which is just published.

**Comment by realOxy** [comment]
> 1.13.6 is the first version which is just published.

Oh, sorry. I just noticed this

**Comment by licaon-kter** [comment]
building 1.14.0-alpha09 locally now

**Comment by licaon-kter** [comment]
diff log :( 
[Uploading m3u941.log…]()

**Comment by realOxy** [comment]
@licaon-kter why...

**Comment by linsui** [comment]
Is your apk built with GitHub Action?

**Comment by realOxy** [comment]
> Is your apk built with GitHub Action?

No, I built them in my own Mac, the GitHub action is merged from other contributors. They are useless to me. I have not styled GitHub action :(

**Comment by linsui** [comment]
Currently it builds the debug apk. Maybe we can try building the release apk with it and compare it with the fdroid apk. https://github.com/realOxy/M3UAndroid/blob/master/.github/workflows/android.yml#L27

**Comment by realOxy** [comment]
> Currently it builds the debug apk. Maybe we can try building the release apk with it and compare it with the fdroid apk. https://github.com/realOxy/M3UAndroid/blob/master/.github/workflows/android.yml#L27

Does it means I should change it to androidApp:assembleRelease ?

**Comment by realOxy** [comment]
Do I need to publish a new release after changing it?

**Comment by linsui** [comment]
> Does it means I should change it to androidApp:assembleRelease ?

Yes.

> Do I need to publish a new release after changing it?

No, we just need to check the apk.

**Comment by realOxy** [comment]
@linsui Hi, I have pushed it. Yesterday I merged a PR which has an android resource file changed and a fastlane metadata file changed, I just revert the android resource commit.

**Comment by linsui** [comment]
Your apk is in https://github.com/realOxy/M3UAndroid/actions/runs/7551132575/artifacts/1174212234. Our apk is in https://gitlab.com/linsui/fdroiddata/-/jobs/5945007947/artifacts/file/tmp/com.m3u.androidApp_94.apk. They have lots of diff. Weird...

**Comment by realOxy** [comment]
@linsui What compare tool you used
<img width="1470" alt="image" src="https://github.com/realOxy/M3UAndroid/assets/70512220/74930ab7-f584-4c03-a1c0-b5f6f7276d7f">
I compared them in android studio

**Comment by licaon-kter** [comment]
Use apktool to disassemble each APK first, remove META-INF, original and apktool.yml, then use `diff -ru` or better yet `diffoscope` between the folders.

Or just feed the APKs to the diffoscope site :)

**Comment by realOxy** [comment]
Hi, I use apktool d, remove META-INF, original and apktool.yml, and use pkgdiff -d.
Get this result:

[pkgdiff_reports.zip](https://github.com/realOxy/M3UAndroid/files/13960578/pkgdiff_reports.zip)

**Comment by licaon-kter** [comment]
which apks did you compare? links pls

**Comment by realOxy** [comment]
right: https://gitlab.com/linsui/fdroiddata/-/jobs/5945007947/artifacts/file/tmp/com.m3u.androidApp_94.apk

**Comment by licaon-kter** [comment]
Yup confirmed the same difference locally
```
│ │   --- m3u_94_githubci/unknown/kotlin-tooling-metadata.json
│ ├── +++ com.m3u.androidApp_94/unknown/kotlin-tooling-metadata.json
│ │ │ +    "buildSystemVersion": "8.4",
│ │ │ -    "buildSystemVersion": "8.5",
```

so you are close :)

Also... makes us think about why your Mac is outputting un-repro builds :(

**Comment by licaon-kter** [comment]
Should be okay too, now you need to hunt for that difference, `buildSystemVersion`

**Comment by realOxy** [comment]
buildSystemVersion is a cli command? I cannot execute it.
My Mac is MBA M2 Sonoma 14.2.1

**Comment by realOxy** [comment]
Oh sorry, It is Gradle. I forgot

**Comment by realOxy** [comment]
Now I re-compare diff between the f-droid generated APK and Mac generated APK.

[pkgdiff_reports.f-d_to_local.zip](https://github.com/realOxy/M3UAndroid/files/13961843/pkgdiff_reports.f-d_to_local.zip)
It seems only has one diff.
https://en.wikipedia.org/wiki/.DS_Store

**Comment by licaon-kter** [comment]
Which links?

**Comment by realOxy** [comment]
> Which links?

left: https://gitlab.com/linsui/fdroiddata/-/jobs/5945007947/artifacts/file/tmp/com.m3u.androidApp_94.apk
right: Same commit in my Mac

I just push a new ci commit, maybe can solve the Gradle version mistake. We should restart ci and then check them again.

**Comment by realOxy** [comment]
hmmmm, failed..

**Comment by licaon-kter** [comment]
> right: Same commit in my Mac

you mean https://github.com/realOxy/M3UAndroid/releases/tag/v1.14.0-alpha09 this one published 19h ago?

**Comment by realOxy** [comment]
> > right: Same commit in my Mac
> 
> you mean https://github.com/realOxy/M3UAndroid/releases/tag/v1.14.0-alpha09 this one published 19h ago?

I am not sure, but Now I get their Md5, They are different.

**Comment by realOxy** [comment]
> > hmmmm, failed..
> 
> I guess you should run `./gradlew`

OK, let me try.

**Comment by realOxy** [comment]
@linsui CI now passed. Should I publish a new version?

**Comment by realOxy** [comment]
> @realOxy just say which commit and post a link to the APK so we can test

OK, based latest commit:

![androidApp-release apk](https://github.com/realOxy/M3UAndroid/assets/70512220/08a0a001-58a2-4e24-8d46-6aecb5f33795)

Should be renamed.

**Comment by realOxy** [comment]
@licaon-kter Based on latest commit:
https://tmpfiles.org/3893637/androidapp-release.apk

**Comment by linsui** [comment]
No, we can get it from the artifact.

**Comment by linsui** [comment]
The apk built by the GitHub CI is reproducible. :) Maybe the AS or MacOS causes difference...

**Comment by licaon-kter** [comment]
@realOxy link says `404 Not Found`

**Comment by realOxy** [comment]
@licaon-kter 
https://docs.google.com/uc?export=download&id=1jGppZ4sevgHr2FiDvcFcDQufjO9KF3ka

**Comment by realOxy** [comment]
@licaon-kter @linsui 
Thanks for your help!
I have released a new update.
https://github.com/realOxy/M3UAndroid/releases/tag/v1.14.0-alpha10

**Comment by licaon-kter** [comment]
`{"metadata":{"generated":"2024-01-21T10:53:32.455Z"},...`

https://gitlab.com/fdroid/fdroiddata/-/jobs/5977778365#L2150

The MikePenz AboutLicenses lib needs to NOT add a time stamp

@linsui do you have a snippet at hand on how to do that? I know it exists but not sure where it was applied

**Comment by realOxy** [comment]
@licaon-kter Hello, I have fixed it (https://github.com/mikepenz/AboutLibraries/issues/784#issuecomment-1205501876) and release a new package

**Comment by licaon-kter** [comment]
verified locally, thanks

**Comment by realOxy** [comment]
@licaon-kter @linsui Hi, Does f-droid allow local AAR files? I want to add exoplayer ffmpeg support.

**Comment by licaon-kter** [comment]
You mean if we build the .AAR first in the recipe? Yes.,..

**Comment by linsui** [comment]
You can search in fdroiddata. There are some other apps building exoplayer.

**Comment by realOxy** [comment]
Hi, I have enabled ABI splits and added two flavors (full and snapshot, snapshot is only for Github Action Build Artifact) in latest commits. ABI splits will be disabled when it is built for benchmark or the "snapshot" flavor.
I want to know is F-droid allowed ABI splits APKs(include universal one) and will the F-droid action run "assembleFullRelease"?

**Comment by licaon-kter** [comment]
We can update the recipe, yes ;)

**Comment by licaon-kter** [comment]
To be able to split ABI per arch we need to have separate versionCodes per ABI, eg: https://codeberg.org/iNPUTmice/Conversations/src/branch/master/build.gradle#L253

**Comment by realOxy** [comment]
Can we disable split and use richCodec flavor for f-ndroid?

**Comment by realOxy** [comment]
richCodec flavor and stableChannel flavor

**Comment by licaon-kter** [comment]
already did :wink: https://gitlab.com/fdroid/fdroiddata/-/commit/7f332730a8317a32922180023453817405c1e917
